### PR TITLE
Update Header Links

### PR DESCRIPTION
**Pull request by TylerHobanDotCom**
add github and privatebin in header to all pages

### CODE REVIEW

**Comment by TylerHobanDotCom** [comment]
merge at like 8 am

**Comment by TylerHobanDotCom** [comment]
im going clinically insane after dealing with the server bullshit for the last few hours

**Comment by TylerHobanDotCom** [comment]
rape apache

**Review by levelfourtwenty — APPROVED** [review]
I don't see any issues with this, merging.

**Pull request merged**
